all:
  exifhosts:
    debian:
      hosts:
        server1:
          ansible_host: 10.0.0.1
          exiftool_dldir: "/tmp/exiftool"
          exif_user: root
          exif_group: root
    ubuntu:
      hosts:
        server2:
          ansible_connection: 10.0.0.2
          exiftool_dldir: "/tmp/exiftool"
          exif_user: root
          exif_group: root
    synology:
      hosts:
        nas1:
          ansible_host: 10.0.0.2
          ansible_port: 22022
          exiftool_dldir: "/volume1/dl/exiftool"
          exif_user: 501
          exif_group: 20